"""empty message

Revision ID: af6c373b96a5
Revises: 679e14b21342
Create Date: 2022-09-10 01:00:51.878728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6c373b96a5'
down_revision = '679e14b21342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('puzzle_image1', sa.String(length=400), nullable=True))
    op.add_column('puzzle', sa.Column('puzzle_image2', sa.String(length=400), nullable=True))
    op.add_column('puzzle', sa.Column('puzzle_image3', sa.String(length=400), nullable=True))
    op.drop_column('puzzle', 'puzzle_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('puzzle_image', sa.VARCHAR(length=400), nullable=True))
    op.drop_column('puzzle', 'puzzle_image3')
    op.drop_column('puzzle', 'puzzle_image2')
    op.drop_column('puzzle', 'puzzle_image1')
    # ### end Alembic commands ###
