"""empty message

Revision ID: 0331448d609e
Revises: 088aa5d64c23
Create Date: 2022-09-14 13:28:04.500383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0331448d609e'
down_revision = '088aa5d64c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('has_key_a', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('selected_key_a', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('solved_gate_keyhole', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('has_coin', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('selected_coin', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('solved_address_screws', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('saw_address', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('saw_address_hidden_symbols', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('mailbox_box_correct_combination', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('mailbox_box_combination_entered', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('solved_mailbox_box', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('has_red_gem', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('has_blue_gem', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('has_green_gem', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('has_yellow_gem', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('selected_red_gem', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('selected_blue_gem', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('selected_green_gem', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('selected_yellow_gem', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('saw_fountain_bench_animals', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('solved_wall_fountains', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('has_telescope_lens', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('selected_telescope_lens', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('solved_carved_trees_no_order', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('solved_house_door_key', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('saw_toolbox_note', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('has_magnet', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('selected_magnet', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('has_key_b', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('selected_key_b', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('solved_toolbox', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('has_key_c', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('selected_key_c', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('solved_fountain_door', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('has_knife', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('selected_knife', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('solved_fountain_bench_pillow', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('saw_carved_trees', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('saw_compass_mosaic', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('solved_flower_gate_padlock', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'solved_flower_gate_padlock')
    op.drop_column('player', 'saw_compass_mosaic')
    op.drop_column('player', 'saw_carved_trees')
    op.drop_column('player', 'solved_fountain_bench_pillow')
    op.drop_column('player', 'selected_knife')
    op.drop_column('player', 'has_knife')
    op.drop_column('player', 'solved_fountain_door')
    op.drop_column('player', 'selected_key_c')
    op.drop_column('player', 'has_key_c')
    op.drop_column('player', 'solved_toolbox')
    op.drop_column('player', 'selected_key_b')
    op.drop_column('player', 'has_key_b')
    op.drop_column('player', 'selected_magnet')
    op.drop_column('player', 'has_magnet')
    op.drop_column('player', 'saw_toolbox_note')
    op.drop_column('player', 'solved_house_door_key')
    op.drop_column('player', 'solved_carved_trees_no_order')
    op.drop_column('player', 'selected_telescope_lens')
    op.drop_column('player', 'has_telescope_lens')
    op.drop_column('player', 'solved_wall_fountains')
    op.drop_column('player', 'saw_fountain_bench_animals')
    op.drop_column('player', 'selected_yellow_gem')
    op.drop_column('player', 'selected_green_gem')
    op.drop_column('player', 'selected_blue_gem')
    op.drop_column('player', 'selected_red_gem')
    op.drop_column('player', 'has_yellow_gem')
    op.drop_column('player', 'has_green_gem')
    op.drop_column('player', 'has_blue_gem')
    op.drop_column('player', 'has_red_gem')
    op.drop_column('player', 'solved_mailbox_box')
    op.drop_column('player', 'mailbox_box_combination_entered')
    op.drop_column('player', 'mailbox_box_correct_combination')
    op.drop_column('player', 'saw_address_hidden_symbols')
    op.drop_column('player', 'saw_address')
    op.drop_column('player', 'solved_address_screws')
    op.drop_column('player', 'selected_coin')
    op.drop_column('player', 'has_coin')
    op.drop_column('player', 'solved_gate_keyhole')
    op.drop_column('player', 'selected_key_a')
    op.drop_column('player', 'has_key_a')
    # ### end Alembic commands ###
