"""empty message

Revision ID: 23be90259e0c
Revises: ceeae1dc0c1e
Create Date: 2022-09-16 00:00:09.919109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23be90259e0c'
down_revision = 'ceeae1dc0c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('solved_berry_bush', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'solved_berry_bush')
    # ### end Alembic commands ###
