"""empty message

Revision ID: 5b0cfae1c7b5
Revises: 784c44c595a2
Create Date: 2022-09-14 17:16:52.530110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0cfae1c7b5'
down_revision = '784c44c595a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('selected_item', sa.Integer(), nullable=True))
    op.drop_column('player', 'selected_key_b')
    op.drop_column('player', 'selected_key_c')
    op.drop_column('player', 'selected_yellow_gem')
    op.drop_column('player', 'selected_red_gem')
    op.drop_column('player', 'selected_knife')
    op.drop_column('player', 'selected_magnet')
    op.drop_column('player', 'selected_key_a')
    op.drop_column('player', 'selected_coin')
    op.drop_column('player', 'selected_blue_gem')
    op.drop_column('player', 'selected_green_gem')
    op.drop_column('player', 'selected_telescope_lens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('selected_telescope_lens', sa.BOOLEAN(), nullable=True))
    op.add_column('player', sa.Column('selected_green_gem', sa.BOOLEAN(), nullable=True))
    op.add_column('player', sa.Column('selected_blue_gem', sa.BOOLEAN(), nullable=True))
    op.add_column('player', sa.Column('selected_coin', sa.BOOLEAN(), nullable=True))
    op.add_column('player', sa.Column('selected_key_a', sa.BOOLEAN(), nullable=True))
    op.add_column('player', sa.Column('selected_magnet', sa.BOOLEAN(), nullable=True))
    op.add_column('player', sa.Column('selected_knife', sa.BOOLEAN(), nullable=True))
    op.add_column('player', sa.Column('selected_red_gem', sa.BOOLEAN(), nullable=True))
    op.add_column('player', sa.Column('selected_yellow_gem', sa.BOOLEAN(), nullable=True))
    op.add_column('player', sa.Column('selected_key_c', sa.BOOLEAN(), nullable=True))
    op.add_column('player', sa.Column('selected_key_b', sa.BOOLEAN(), nullable=True))
    op.drop_column('player', 'selected_item')
    # ### end Alembic commands ###
