"""empty message

Revision ID: 679e14b21342
Revises: 3470863a38b3
Create Date: 2022-09-10 00:05:59.737212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679e14b21342'
down_revision = '3470863a38b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_puzzle',
    sa.Column('player_puzzle_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=False),
    sa.Column('player_saw_puzzle', sa.Boolean(), nullable=True),
    sa.Column('player_completed_puzzle', sa.Boolean(), nullable=True),
    sa.Column('combination_player_entered', sa.String(), nullable=True),
    sa.Column('correct_combination', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzle.puzzle_id'], ),
    sa.PrimaryKeyConstraint('player_puzzle_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_puzzle')
    # ### end Alembic commands ###
