"""empty message

Revision ID: 784c44c595a2
Revises: 88f6e3c61edd
Create Date: 2022-09-14 16:21:27.098878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784c44c595a2'
down_revision = '88f6e3c61edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('wall_fountains_correct_combination', sa.String(length=10), nullable=True))
    op.add_column('player', sa.Column('wall_fountains_combination_entered', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'wall_fountains_combination_entered')
    op.drop_column('player', 'wall_fountains_correct_combination')
    # ### end Alembic commands ###
