"""empty message

Revision ID: 88f6e3c61edd
Revises: 0331448d609e
Create Date: 2022-09-14 13:40:54.311475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f6e3c61edd'
down_revision = '0331448d609e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('flower_gate_padlock_correct_combination', sa.String(length=10), nullable=True))
    op.add_column('player', sa.Column('flower_gate_padlock_combination_entered', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'flower_gate_padlock_combination_entered')
    op.drop_column('player', 'flower_gate_padlock_correct_combination')
    # ### end Alembic commands ###
