"""empty message

Revision ID: 963fd52dcbc8
Revises: 5b0cfae1c7b5
Create Date: 2022-09-14 17:19:05.207231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963fd52dcbc8'
down_revision = '5b0cfae1c7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'selected_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('selected_item', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
