"""empty message

Revision ID: ad9cd0e8dd64
Revises: b677cdf69ba2
Create Date: 2022-09-11 17:52:15.253198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9cd0e8dd64'
down_revision = 'b677cdf69ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('new_game', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'new_game')
    # ### end Alembic commands ###
