"""empty message

Revision ID: ceeae1dc0c1e
Revises: 963fd52dcbc8
Create Date: 2022-09-14 17:19:16.434076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceeae1dc0c1e'
down_revision = '963fd52dcbc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('selected_item', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'selected_item')
    # ### end Alembic commands ###
